### ISSUE TITLE
pypi package lacks less files

### ISSUE THREAD

**Issue by gregoire-astruc** [InfoAgeTech/django-awesome-bootstrap#5]
Hello,

the package currently present at PyPI lacks some less files, preventing us from using those resources.

**Comment by troygrosfield** [comment]
See the note on the readme of the main repo:

> There are better ways to manage static assets for your django projects. I recommend using a package manager such as bower. If someone wants to take ownership of this repo reach out to me and I'll gladly transfer ownership. Otherwise, this repo will no longer be updated.
