### ISSUE TITLE
bootstrap 3.3.0, font-awesome 4.2.0

### ISSUE THREAD

**Issue by gregoire-astruc** [InfoAgeTech/django-awesome-bootstrap#6]
Any chance of having them updated and pushed to PyPI O:-) ?

**Comment by troygrosfield** [comment]
See the note on the readme of the main repo:

> There are better ways to manage static assets for your django projects. I recommend using a package manager such as bower. If someone wants to take ownership of this repo reach out to me and I'll gladly transfer ownership. Otherwise, this repo will no longer be updated.
